# Generated by Django 2.2.3 on 2022-08-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
