# Generated by Django 2.2.3 on 2022-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appservicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
