# Generated by Django 2.2.3 on 2022-08-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appservicios', '0002_servicios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
